---
- name: Collect distribution facts
  setup:
    gather_subset:
      - min

- name: Set facts for CentOS and Red Hat Enterprise Linux (RHEL)
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'Red Hat Enterprise Linux'
  block:
    - name: Set distribution codename fact for CentOS and RHEL
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_release']|title ] }}

    - name: Set distribution id for CentOS and RHEL
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_major_version'] ] }}

- name: Set facts for Debian, e.g. Debian 10 (Buster) or Debian 11 (Bullseye)
  when: ansible_facts['distribution'] == 'Debian'
  block:
    # if the host's Debian branch does have a codename, e.g. VERSION_CODENAME is set in /etc/os-release, or it does not
    # have a codename, but lsb_release is available on that host, then ansible_facts['distribution_release'] is set.
    - name: Set distribution codename fact for Debian releases with codenames, e.g. Debian 10 (Buster) or Debian 11 (Bullseye)
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_release']|title ] }}
      when: ansible_facts['distribution_release'] != 'NA'

    # if the host's Debian branch does not have a codename, e.g. no VERSION_CODENAME in /etc/os-release, and lsb_release
    # is not available on that host, then ansible_facts['distribution_release'] is 'NA'
    - name: Set distribution codename fact for future Debian releases where distribution release fact is 'NA'
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution'], 'NA' ] }}
      when: ansible_facts['distribution_release'] == 'NA'

    # if the host's Debian branch does have a version number, e.g. VERSION_ID is set in /etc/os-release, then
    # ansible_facts['distribution_major_version'] is a number
    - name: Set distribution id fact for past and current Debian releases, e.g. Debian 10 (Buster)
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_major_version'] ] }}
      when: ansible_facts['distribution_major_version'] is number

    # if the host's Debian branch does not have a version number, e.g. VERSION_ID is not set in /etc/os-release, and
    # lsb_release is not available on that host, ansible_facts['distribution_major_version'] is 'NA'
    - name: Set distribution id fact for future Debian releases if lsb_release is not installed
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_major_version'] ] }}
      when: ansible_facts['distribution_major_version'] == 'NA'

    # if the host's Debian branch does not have a version number, e.g. VERSION_ID is not set in /etc/os-release, but
    # lsb_release is available on that host, ansible_facts['distribution_major_version'] is e.g. 'testing'
    - name: Set distribution id fact for future Debian releases if lsb_release is installed
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_major_version']|title ] }}
      when: ansible_facts['distribution_major_version'] is not number and
            ansible_facts['distribution_major_version'] != 'NA'

- name: Set facts for Ubuntu, e.g. Ubuntu 18.04 LTS (Bionic Beaver) or Ubuntu 20.04 LTS (Focal Fossa)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Set distribution codename fact for Ubuntu releases
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_release']|title ] }}

    - name: Set distribution id fact for Ubuntu
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution'], ansible_facts['distribution_version'] ] }}
