---
- name: Collect distribution facts
  setup:
    gather_subset:
      - min

- name: Load variables specific to Debian and its derivatives, e.g. Debian 10 (Buster) or Ubuntu 20.04 LTS (Focal Fossa)
  include_vars: '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Load tasks specific to OS
  include_tasks: 'setup-{{ ansible_distribution }}.yml'
  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
