---
- debug:
    msg: 
    - "ansible_distribution:         {{ ansible_distribution }}"
    - "ansible_distribution_release: {{ ansible_distribution_release }}"
    - "ansible_distribution_version: {{ ansible_distribution_version }}"

- import_tasks: setup-Debian.yml
  become: yes
  when: ansible_os_family == 'Debian'
