---
- name: Collect distribution facts
  setup:
    gather_subset:
      - min

- name: Set facts for CentOS and Red Hat Enterprise Linux (RHEL)
  when: ansible_facts['distribution'] == 'CentOS' or ansible_facts['distribution'] == 'Red Hat Enterprise Linux'
  block:
    - name: Set distribution codename fact for CentOS and RHEL
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_release']|title ] }}

    - name: Set distribution id for CentOS and RHEL
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_major_version'] ] }}

- name: Set facts for Debian, e.g. Debian 10 (Buster)
  when: ansible_facts['distribution'] == 'Debian'
  block:
    - name: Set distribution codename fact for known Debian releases
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_release']|title ] }}
      when: ansible_facts['distribution_release'] != 'NA'

    # ansible_facts['distribution_version'] is either in format "9.0" or "buster/sid"

    - name: Set distribution codename fact for unknown Debian releases where distribution version fact is not a number
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_version'].split('/')[0]|title ] }}
      when: ansible_facts['distribution_release'] == 'NA' and not ansible_facts['distribution_version'] is number

    - name: Set distribution codename fact for unknown Debian releases where distribution version fact is a number
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_version'].split('.')[0] ] }}
      when: ansible_facts['distribution_release'] == 'NA' and ansible_facts['distribution_version'] is number

    - name: Set distribution id fact for Debian
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_major_version'] ] }}

- name: Set facts for Ubuntu, e.g. Ubuntu 20.04 LTS (Focal Fossa)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Set distribution codename fact for Ubuntu releases
      set_fact:
        distribution_codename: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_release']|title ] }}

    - name: Set distribution id fact for Ubuntu
      set_fact:
        distribution_id: |
            {{ [ ansible_facts['distribution']|title, ansible_facts['distribution_version'] ] }}
