---
- name: Collect distribution facts
  setup:
    gather_subset:
      - min

- debug:
    msg:
    - "ansible_os_family:            {{ ansible_os_family }}"
    - "ansible_distribution:         {{ ansible_distribution }}"
    - "ansible_distribution_release: {{ ansible_distribution_release }}"
    - "ansible_distribution_version: {{ ansible_distribution_version }}"

- name: Load tasks specific for Debian
  import_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- name: Load tasks specific for Ubuntu
  import_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
